title: El Salvador its just Amazing
author: emelysalmeron
email: your-email@domain.com
description:
 This website its for you to know an geographical small country but full of amazing people and places to visit. You will meet virtually peoples of good hearts and very good places that will leave shocked. 
> # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
